name = input("Your name: ")
print ('hi',name)
print('Enter only numbers')
print('Enter a value')
y = input('y: ')
print('Thank you enter value 2')
x = input('x: ')
sum = int(x) + int(y)
print('Answer', sum)
print("thank you for using this bot")
print("produced by 1to5PC")
